# Generated by Django 5.2 on 2025-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biografia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='email',
            field=models.EmailField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
