# Generated by Django 5.2 on 2025-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biografia', '0002_convidado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='nome',
            field=models.CharField(default='nome', max_length=100),
            preserve_default=False,
        ),
    ]
